### PR TITLE
Add GHA test and release workflows

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #6

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse, two notes:
 - Looks like `stackprof` gem (which `rambling-trie` depends on) doesn't support windows https://github.com/tmm1/stackprof#requirements, let me know if this need to be investigated deeper.
 - I have added `release-tag` workflow which will allow manual release,  let me know how do you think about it?

**Comment by ronaldtse** [comment]
@CAMOBAP stackprof is clearly not useful in a running environment, can you help disable it on windows completely and also make it a dev time dependency?

**Comment by CAMOBAP** [comment]
@ronaldtse thanks for information

> can you help disable it on windows completely 

ok

> and also make it a dev time dependency?

It's already dev one

P.S. some tests failed I will check why

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Pull request merged**
